[package]
name = "bruto"
version = "0.1.0"
edition = "2021"
authors = ["Mate Kovacs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
